import { PUZZLES } from "./puzzles.js";

const COLORS=["#fca5a5","#fdba74","#fde68a","#86efac","#67e8f9","#93c5fd","#c4b5fd","#f0abfc","#f9a8d4","#d9f99d","#a7f3d0","#bfdbfe","#ddd6fe","#fecdd3","#e2e8f0"];
const ALPHABET="0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ";
const STORAGE_KEY="queens-archive-stats:v3";
const TRANSFORMS=[
 ["identity",(r,c,n)=>[r,c]],["rotate 90",(r,c,n)=>[c,n-1-r]],["rotate 180",(r,c,n)=>[n-1-r,n-1-c]],["rotate 270",(r,c,n)=>[n-1-c,r]],
 ["mirror horizontal",(r,c,n)=>[r,n-1-c]],["mirror vertical",(r,c,n)=>[n-1-r,c]],["transpose",(r,c)=>[c,r]],["anti-transpose",(r,c,n)=>[n-1-c,n-1-r]]
];
const $=s=>document.querySelector(s), boardEl=$("#board"),selectEl=$("#puzzleSelect"),randomSizeEl=$("#randomSize"),randomButton=$("#randomButton"),statusEl=$("#status"),metaEl=$("#meta"),statsEl=$("#stats"),timerEl=$("#timer"),ratingPanel=$("#ratingPanel"),clearButton=$("#clearButton"),checkButton=$("#checkButton"),hintButton=$("#hintButton"),solutionButton=$("#solutionButton"),exportStatsButton=$("#exportStatsButton");
let activePuzzle=PUZZLES[0],marks=[],showSolution=false,checkMode=false,hint=null,hintCount=0,solvedLogged=false,timerStartedAt=null,elapsed=0,timerHandle=null,stats=loadStats(),randomCounter=0;
const rowOf=(i,n)=>Math.floor(i/n),colOf=(i,n)=>i%n,idxOf=(r,c,n)=>r*n+c;
const queenIndices=(state=marks)=>state.map((v,i)=>v==="q"?i:-1).filter(i=>i>=0);
const solutionSet=p=>new Set([...p.solution].map((v,i)=>v==="Q"?i:-1).filter(i=>i>=0));
const unique=a=>[...new Set(a)];

function populateSelect(){selectEl.innerHTML="";for(const p of PUZZLES){const o=document.createElement("option");o.value=p.id;o.textContent=`Day ${p.day} · ${p.size}×${p.size}`;selectEl.append(o)}}
function loadPuzzle(p,value=p.id){activePuzzle=p;marks=Array(p.size*p.size).fill("");showSolution=checkMode=false;hint=null;hintCount=0;solvedLogged=false;solutionButton.textContent="Show solution";checkButton.textContent="Check";resetTimer();if([...selectEl.options].some(o=>o.value===value))selectEl.value=value;render()}
function render(){const n=activePuzzle.size;boardEl.style.gridTemplateColumns=`repeat(${n},1fr)`;boardEl.style.gridTemplateRows=`repeat(${n},1fr)`;boardEl.innerHTML="";const errors=findErrors(checkMode),answer=solutionSet(activePuzzle);for(let r=0;r<n;r++)for(let c=0;c<n;c++){const i=idxOf(r,c,n),region=activePuzzle.regions[i],cell=document.createElement("button");cell.type="button";cell.className="cell";cell.dataset.state=marks[i];cell.style.background=COLORS[regionNumber(region)%COLORS.length];applyBorders(cell,r,c,i,region,n);if(errors.has(i))cell.classList.add("error");if(hint?.target===i){cell.classList.add("hint-target");cell.dataset.hintAction=hint.action}if(hint?.causes?.includes(i))cell.classList.add("hint-cause");if(showSolution&&answer.has(i)&&marks[i]!=="q")cell.classList.add("solution");cell.addEventListener("click",()=>{startTimer();marks[i]=marks[i]===""?"x":marks[i]==="x"?"q":"";hint=null;checkMode=false;render()});boardEl.append(cell)}renderStatus();renderStats();renderRating();metaEl.textContent=metaText(activePuzzle)}
function applyBorders(cell,r,c,i,region,n){const thick="4px",thin="1px";cell.style.borderTopWidth=r===0||activePuzzle.regions[i-n]!==region?thick:thin;cell.style.borderBottomWidth=r===n-1||activePuzzle.regions[i+n]!==region?thick:thin;cell.style.borderLeftWidth=c===0||activePuzzle.regions[i-1]!==region?thick:thin;cell.style.borderRightWidth=c===n-1||activePuzzle.regions[i+1]!==region?thick:thin}
function regionNumber(x){const i=ALPHABET.indexOf(x);return i>=0?i:x.codePointAt(0)}
function metaText(p){return `${p.source??"archive"}${p.templateDay?` · template day ${p.templateDay}`:""}${p.transformName?` · ${p.transformName}`:""}`}

function findErrors(checkSolution=false){const n=activePuzzle.size,q=queenIndices(),bad=new Set(),rows=new Map(),cols=new Map(),regions=new Map(),answer=solutionSet(activePuzzle);for(const i of q){duplicate(rows,rowOf(i,n),i,bad);duplicate(cols,colOf(i,n),i,bad);duplicate(regions,activePuzzle.regions[i],i,bad);if(checkSolution&&!answer.has(i))bad.add(i)}for(let a=0;a<q.length;a++)for(let b=a+1;b<q.length;b++)if(Math.max(Math.abs(rowOf(q[a],n)-rowOf(q[b],n)),Math.abs(colOf(q[a],n)-colOf(q[b],n)))<=1){bad.add(q[a]);bad.add(q[b])}if(checkSolution)for(const i of answer)if(marks[i]==="x")bad.add(i);return bad}
function duplicate(map,key,i,bad){if(map.has(key)){bad.add(map.get(key));bad.add(i)}else map.set(key,i)}
function solved(){const a=solutionSet(activePuzzle);return marks.every((v,i)=>a.has(i)?v==="q":v!=="q")}
function renderStatus(){statusEl.className="status";if(hint){statusEl.innerHTML=`<span class="technique">${escapeHtml(hint.technique)}</span>${escapeHtml(hint.message)}`;return}const e=findErrors(false);if(e.size){statusEl.classList.add("bad");statusEl.textContent="Conflict: queens share a row, column, region, or touch.";return}if(checkMode&&findErrors(true).size){statusEl.classList.add("bad");statusEl.textContent="Some marks contradict the stored solution.";return}if(solved()){statusEl.classList.add("ok");statusEl.textContent=`Solved in ${formatTime(currentMs())} · ${hintCount} hints`;finishSolve();return}statusEl.textContent=`${queenIndices().length}/${activePuzzle.size} queens · ${hintCount} hints`}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]))}

function nextHumanStep(p,state){return conflictStep(p,state)||queenExclusionStep(p,state)||singleStep(p,state)||lockedCandidatesStep(p,state)||commonAttackStep(p,state)||hallSetStep(p,state,2)||hallSetStep(p,state,3)||null}
function conflictStep(p,state){const n=p.size,q=queenIndices(state);for(let a=0;a<q.length;a++)for(let b=a+1;b<q.length;b++){const x=q[a],y=q[b];if(rowOf(x,n)===rowOf(y,n))return step("Conflict",y,"clear",[x],`Remove this queen: row ${rowOf(x,n)+1} already has one.`);if(colOf(x,n)===colOf(y,n))return step("Conflict",y,"clear",[x],`Remove this queen: column ${colOf(x,n)+1} already has one.`);if(p.regions[x]===p.regions[y])return step("Conflict",y,"clear",[x],"Remove this queen: its color region already has one.");if(Math.max(Math.abs(rowOf(x,n)-rowOf(y,n)),Math.abs(colOf(x,n)-colOf(y,n)))<=1)return step("Touching queens",y,"clear",[x],"Remove this queen: queens may not touch, even diagonally.")}return null}
function queenExclusionStep(p,state){for(const q of queenIndices(state))for(let i=0;i<state.length;i++)if(state[i]===""&&attacks(p,q,i)){let reason=rowOf(q,p.size)===rowOf(i,p.size)?`row ${rowOf(q,p.size)+1}`:colOf(q,p.size)===colOf(i,p.size)?`column ${colOf(q,p.size)+1}`:p.regions[q]===p.regions[i]?"the same color region":"an adjacent square";return step("Queen exclusion",i,"x",[q],`Put X here: the highlighted queen rules out ${reason}.`)}return null}
function candidateSet(p,state){const q=queenIndices(state),set=new Set();for(let i=0;i<state.length;i++){if(state[i]==="x")continue;if(state[i]==="q"||q.every(x=>!attacks(p,x,i)))set.add(i)}return set}
function units(p){const n=p.size,out=[];for(let r=0;r<n;r++)out.push({type:"row",key:r,label:`row ${r+1}`,cells:[...Array(n)].map((_,c)=>idxOf(r,c,n))});for(let c=0;c<n;c++)out.push({type:"column",key:c,label:`column ${c+1}`,cells:[...Array(n)].map((_,r)=>idxOf(r,c,n))});for(const reg of unique([...p.regions]))out.push({type:"region",key:reg,label:`${colorName(reg)} region`,cells:[...p.regions].map((v,i)=>v===reg?i:-1).filter(i=>i>=0)});return out}
function colorName(reg){return `color ${regionNumber(reg)+1}`}
function singleStep(p,state){const cand=candidateSet(p,state);for(const u of units(p)){if(u.cells.some(i=>state[i]==="q"))continue;const possible=u.cells.filter(i=>cand.has(i));if(possible.length===1)return step("Single candidate",possible[0],"q",possible,`Place a queen here: ${u.label} has only one legal square left.`)}return null}
function lockedCandidatesStep(p,state){const cand=candidateSet(p,state),all=units(p);for(const source of all){if(source.cells.some(i=>state[i]==="q"))continue;const poss=source.cells.filter(i=>cand.has(i));if(poss.length<2)continue;for(const target of all){if(target.type===source.type)continue;if(!poss.every(i=>target.cells.includes(i)))continue;const elim=target.cells.find(i=>state[i]===""&&cand.has(i)&&!poss.includes(i));if(elim!=null)return step("Locked candidates",elim,"x",poss,`All candidates for ${source.label} lie in ${target.label}; the rest of ${target.label} is excluded.`)}}return null}
function commonAttackStep(p,state){const cand=candidateSet(p,state);for(const u of units(p)){if(u.cells.some(i=>state[i]==="q"))continue;const poss=u.cells.filter(i=>cand.has(i));if(poss.length<2||poss.length>5)continue;for(let target=0;target<state.length;target++){if(state[target]!==""||poss.includes(target)||!cand.has(target))continue;if(poss.every(x=>attacks(p,x,target)))return step("Common attack",target,"x",poss,`Whichever candidate holds the queen in ${u.label}, it attacks this square.`)}}return null}
function hallSetStep(p,state,k){const cand=candidateSet(p,state);for(const type of ["row","column","region"]){const groupUnits=units(p).filter(u=>u.type===type&&!u.cells.some(i=>state[i]==="q")).map(u=>({...u,poss:u.cells.filter(i=>cand.has(i))})).filter(u=>u.poss.length>0&&u.poss.length<=k+1);for(const group of combinations(groupUnits,k)){const union=unique(group.flatMap(u=>u.poss));if(union.length!==k)continue;for(const target of units(p).filter(u=>u.type!==type)){const within=union.filter(i=>target.cells.includes(i));if(within.length!==k)continue;const elim=target.cells.find(i=>state[i]===""&&cand.has(i)&&!union.includes(i));if(elim!=null)return step(k===2?"Locked pair":"Locked triple",elim,"x",union,`${group.map(u=>u.label).join(" and ")} are confined to these ${k} squares, so this square in ${target.label} is excluded.`)}}}return null}
function attacks(p,a,b){if(a===b)return false;const n=p.size;return rowOf(a,n)===rowOf(b,n)||colOf(a,n)===colOf(b,n)||p.regions[a]===p.regions[b]||Math.max(Math.abs(rowOf(a,n)-rowOf(b,n)),Math.abs(colOf(a,n)-colOf(b,n)))<=1}
function step(technique,target,action,causes,message){return{technique,target,action,causes:unique(causes),message}}
function combinations(arr,k){const out=[];function go(start,pick){if(pick.length===k){out.push([...pick]);return}for(let i=start;i<arr.length;i++){pick.push(arr[i]);go(i+1,pick);pick.pop()}}go(0,[]);return out}
function giveHint(){startTimer();checkMode=false;hint=nextHumanStep(activePuzzle,marks);if(!hint){statusEl.className="status bad";statusEl.innerHTML='<span class="technique">No supported deduction</span>This position may need a technique not yet implemented; no answer was revealed.';return}hintCount++;render()}

function transformPuzzle(base){const n=base.size,[name,fn]=TRANSFORMS[Math.floor(Math.random()*TRANSFORMS.length)],regions=Array(n*n),solution=Array(n*n).fill(".");for(let i=0;i<n*n;i++){const[r,c]=fn(rowOf(i,n),colOf(i,n),n),t=idxOf(r,c,n);regions[t]=base.regions[i];if(base.solution[i]==="Q")solution[t]="Q"}const labels=unique(regions),shuffled=shuffle(ALPHABET.slice(0,labels.length).split("")),map=new Map(labels.map((x,i)=>[x,shuffled[i]]));return{id:`random-${n}-${Date.now()}-${++randomCounter}`,source:"archive shuffle",templateDay:base.day,transformName:name,size:n,regions:regions.map(x=>map.get(x)).join(""),solution:solution.join(""),unique:true}}
function createRandom(size){const pool=PUZZLES.filter(p=>p.size===size&&p.unique!==false);if(!pool.length)throw new Error(`No ${size}×${size} templates loaded.`);const withOpening=shuffle(pool).find(p=>nextHumanStep(p,Array(size*size).fill("")))??pool[Math.floor(Math.random()*pool.length)];return transformPuzzle(withOpening)}
function shuffle(a){const x=[...a];for(let i=x.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[x[i],x[j]]=[x[j],x[i]]}return x}

function startTimer(){if(solvedLogged||timerStartedAt!=null)return;timerStartedAt=performance.now();timerHandle=setInterval(renderTimer,250);renderTimer()}function stopTimer(){if(timerStartedAt==null)return;elapsed+=performance.now()-timerStartedAt;timerStartedAt=null;clearInterval(timerHandle);timerHandle=null;renderTimer()}function resetTimer(){timerStartedAt=null;elapsed=0;clearInterval(timerHandle);timerHandle=null;renderTimer()}function currentMs(){return elapsed+(timerStartedAt==null?0:performance.now()-timerStartedAt)}function renderTimer(){timerEl.textContent=formatTime(currentMs())}function formatTime(ms){const s=Math.floor(ms/1000),m=Math.floor(s/60);return m<60?`${String(m).padStart(2,"0")}:${String(s%60).padStart(2,"0")}`:`${Math.floor(m/60)}:${String(m%60).padStart(2,"0")}:${String(s%60).padStart(2,"0")}`}
function loadStats(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY))||{sessions:[],puzzles:{}}}catch{return{sessions:[],puzzles:{}}}}function saveStats(){localStorage.setItem(STORAGE_KEY,JSON.stringify(stats))}function entry(id,create=true){if(!stats.puzzles)stats.puzzles={};if(!stats.puzzles[id]&&create)stats.puzzles[id]={solved:0,best:null,playRating:null,visualRating:null};return stats.puzzles[id]}
function finishSolve(){if(solvedLogged)return;solvedLogged=true;stopTimer();const e=entry(activePuzzle.id);e.solved++;e.best=e.best==null?currentMs():Math.min(e.best,currentMs());stats.sessions.push({id:activePuzzle.id,at:new Date().toISOString(),ms:currentMs(),hints:hintCount});saveStats();renderRating()}
function renderStats(){const e=entry(activePuzzle.id,false);statsEl.textContent=`Best: ${e?.best==null?"—":formatTime(e.best)} · solved: ${e?.solved??0} · all solves: ${stats.sessions?.length??0}`}
function renderRating(){const e=entry(activePuzzle.id,false);ratingPanel.hidden=!(solvedLogged||e);if(ratingPanel.hidden)return;const x=entry(activePuzzle.id);ratingPanel.innerHTML="";ratingPanel.append(ratingRow("Play",x,"playRating"),ratingRow("Visual",x,"visualRating"))}
function ratingRow(label,e,key){const row=document.createElement("div");row.className="rating-row";row.innerHTML=`<span>${label}</span>`;const stars=document.createElement("div");stars.className="stars";for(let i=1;i<=5;i++){const b=document.createElement("button");b.className=`star${i<=(e[key]??0)?" active":""}`;b.textContent="★";b.onclick=()=>{e[key]=i;saveStats();renderRating()};stars.append(b)}row.append(stars);return row}

selectEl.onchange=()=>loadPuzzle(PUZZLES.find(p=>p.id===selectEl.value)??PUZZLES[0]);clearButton.onclick=()=>loadPuzzle(activePuzzle,selectEl.value);checkButton.onclick=()=>{startTimer();checkMode=!checkMode;hint=null;checkButton.textContent=checkMode?"Hide check":"Check";render()};hintButton.onclick=giveHint;solutionButton.onclick=()=>{startTimer();showSolution=!showSolution;solutionButton.textContent=showSolution?"Hide solution":"Show solution";render()};randomButton.onclick=()=>{try{const p=createRandom(Number(randomSizeEl.value)),value="__random__";let o=[...selectEl.options].find(x=>x.value===value);if(!o){o=document.createElement("option");o.value=value;selectEl.prepend(o)}o.textContent=`Random ${p.size}×${p.size} · day ${p.templateDay}`;loadPuzzle(p,value)}catch(e){statusEl.className="status bad";statusEl.textContent=e.message}};exportStatsButton.onclick=()=>{const blob=new Blob([JSON.stringify(stats,null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download="queens-stats.json";a.click();URL.revokeObjectURL(url)};
populateSelect();loadPuzzle(PUZZLES[0]);
